INSERT INTO `teams` (`member_count`, `name`) VALUES
(14, 'Team H');
INSERT INTO `teams` (`member_count`, `name`) VALUES
(14, 'Team KIV'),
(16, 'Team TII');

INSERT INTO `members` (`profile_link`, `name`, `team_id`) VALUES
('http://www.hkt48.jp/profile/23', '秋吉 優花YUKA AKIYOSHI', 1);
INSERT INTO `members` (`profile_link`, `name`, `team_id`) VALUES
('http://www.hkt48.jp/profile/71', '伊藤 優絵瑠YUERU ITO', 1),
('http://www.hkt48.jp/profile/84', '栗山 梨奈RINA KURIYAMA', 1),
('http://www.hkt48.jp/profile/33', '神志那 結衣YUI KOJINA', 1),
('http://www.hkt48.jp/profile/36', '坂口 理子RIKO SAKAGUCHI', 1),
('http://www.hkt48.jp/profile/86', '坂本 りのRINO SAKAMOTO', 1),
('http://www.hkt48.jp/profile/37', '田島 芽瑠MERU TASHIMA', 1),
('http://www.hkt48.jp/profile/48', '田中 美久MIKU TANAKA', 1),
('http://www.hkt48.jp/profile/67', '豊永 阿紀AKI TOYONAGA ', 1),
('http://www.hkt48.jp/profile/11', '松岡 菜摘NATSUMI MATSUOKA', 1),
('http://www.hkt48.jp/profile/90', '水上 凜巳花RIMIKA MIZUKAMI', 1),
('http://www.hkt48.jp/profile/91', '村上 和叶WAKANA MURAKAMI', 1),
('http://www.hkt48.jp/profile/51', '矢吹 奈子NAKO YABUKI', 1),
('http://www.hkt48.jp/profile/75', '渡部 愛加里AKARI WATANABE', 1),
('http://www.hkt48.jp/profile/78', '石橋 颯IBUKI ISHIBASHI', 2),
('http://www.hkt48.jp/profile/79', '市村 愛里AIRI ICHIMURA', 2),
('http://www.hkt48.jp/profile/18', '今田 美奈MINA IMADA', 2),
('http://www.hkt48.jp/profile/60', '運上 弘菜HIRONA UNJO', 2),
('http://www.hkt48.jp/profile/82', '川平 聖HIJIRI KAWAHIRA', 2),
('http://www.hkt48.jp/profile/3', '熊沢 世莉奈SERINA KUMAZAWA', 2),
('http://www.hkt48.jp/profile/6', '下野 由貴YUKI SHIMONO', 2),
('http://www.hkt48.jp/profile/87', '竹本 くるみKURUMI TAKEMOTO', 2),
('http://www.hkt48.jp/profile/88', '田中 伊桜莉IORI TANAKA', 2),
('http://www.hkt48.jp/profile/65', '地頭江 音々NENE JITOE', 2),
('http://www.hkt48.jp/profile/89', '長野 雅MIYABI NAGANO', 2),
('http://www.hkt48.jp/profile/73', '馬場 彩華SAYAKA BABA', 2),
('http://www.hkt48.jp/profile/42', '渕上 舞MAI FUCHIGAMI', 2),
('http://www.hkt48.jp/profile/14', '本村 碧唯AOI MOTOMURA', 2),
('http://www.hkt48.jp/profile/45', '荒巻 美咲MISAKI ARAMAKI', 3),
('http://www.hkt48.jp/profile/56', '今村 麻莉愛MARIA IMAMURA', 3),
('http://www.hkt48.jp/profile/61', '小田 彩加AYAKA ODA', 3),
('http://www.hkt48.jp/profile/46', '栗原 紗英SAE KURIHARA', 3),
('http://www.hkt48.jp/profile/85', '後藤 陽菜乃HINANO GOTO', 3),
('http://www.hkt48.jp/profile/62', '堺 萌香MOEKA SAKAI', 3),
('http://www.hkt48.jp/profile/47', '坂本 愛玲菜ERENA SAKAMOTO', 3),
('http://www.hkt48.jp/profile/72', '石 安伊AI SEKI', 3),
('http://www.hkt48.jp/profile/64', '武田 智加TOMOKA TAKEDA', 3),
('http://www.hkt48.jp/profile/50', '外薗 葉月HAZUKI HOKAZONO', 3),
('http://www.hkt48.jp/profile/57', '松岡 はなHANA MATSUOKA', 3),
('http://www.hkt48.jp/profile/68', '松本 日向HINATA MATSUMOTO ', 3),
('http://www.hkt48.jp/profile/69', '宮崎 想乃SONO MIYAZAKI', 3),
('http://www.hkt48.jp/profile/58', '村川 緋杏BIBIAN MURAKAWA', 3),
('http://www.hkt48.jp/profile/52', '山内 祐奈YUNA YAMAUCHI', 3),
('http://www.hkt48.jp/profile/53', '山下 エミリーEMIRI YAMASHITA', 3);
