CREATE TABLE IF NOT EXISTS teams(
  id INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  member_count INT NOT NULL,
  create_at Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS members(
  id INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
  num INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  profile_link VARCHAR(255) NOT NULL,
  team_id INT NOT NULL,
  create_at Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at Datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(team_id) REFERENCES teams(id)
);
