# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'httparty', '~> 0.20.0'

gem 'nokogiri', '~> 1.13'

gem 'rubocop', '~> 1.25'

gem 'csv', '~> 3.2'
