name: Gin API

on:
  push:
    branches:
      - main

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    services:
      gin_service_db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ginuser
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: gin-service
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: gin_service_db
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.7
    - name: Install golang-migrate CLI
      run: |
        curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
        echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
        sudo apt-get update
        sudo apt-get install -y migrate
    - name: Run Migration
      run: migrate -database="mysql://ginuser:password@tcp(localhost:3306)/gin-service" -path "./db/migrations" --verbose up
    - name: Build
      run: go build -v ./...
    - name: Test
      run: TEST_CLIENT=CI bash -c 'go test ./... -v'

